pull_request_rules:
  - name: Require Dependency Control Team for project.py
    conditions:
      - files~=^project\.py$
    actions:
      request_reviews:
        teams:
          - raghadOrg/dependency-control-team
        required_approvals: 2
